from building import *

cwd = GetCurrentDir()

src = Glob('*.c')

CPPPATH = [cwd]

if GetDepend(['BSP_USING_REMOTE_DT7']):
    group = DefineGroup('Public/Hardware/Remote', src, depend = [''], CPPPATH = CPPPATH)
else:
    group = []

Return('group')
