from building import *

cwd = GetCurrentDir()

src = Glob('*.c')

CPPPATH = [cwd]

if GetDepend(['BSP_USING_LIST']):
    group = DefineGroup('Public/Software/list', src, depend = [''], CPPPATH = CPPPATH)
else:
    group = []

Return('group')
