from building import *

cwd = GetCurrentDir()

src = []
if GetDepend(['BSP_USING_KEY_CALLBACK']):
    src += ['drv_Key_Set.h']
    src += ['func_Key_Record.c']
    if GetDepend(['BSP_USING_KEY_MENU']):
        src += ['mod_KeyCtrl.c']

CPPPATH = [cwd]


if src:
    group = DefineGroup('Public/Software/Menu', src, depend = [''], CPPPATH = CPPPATH)
else:
    group = []


Return('group')
