from building import *

cwd = GetCurrentDir()

src = Glob('*.c')

CPPPATH = [cwd]

if GetDepend(['BSP_USING_SPI_Master']):
    group = DefineGroup('Public/Hardware/SPI_Master', src, depend = [''], CPPPATH = CPPPATH)
else:
    group = []

Return('group')
