from building import *

cwd = GetCurrentDir()

src = Glob('*.c')

CPPPATH = [cwd]

if GetDepend(['BSP_USING_CPU_USAGE']):
    group = DefineGroup('Public/Hardware/Cpu_Usage', src, depend = [''], CPPPATH = CPPPATH)
else:
    group = []

Return('group')
