from building import *

cwd = GetCurrentDir()

src = Glob('*.c')

CPPPATH = [cwd]

if GetDepend(['BSP_USING_RGB_LIGHT']):
    group = DefineGroup('Public/Hardware/Light', src, depend = [''], CPPPATH = CPPPATH)
else:
    group = []

Return('group')
