from building import *

cwd = GetCurrentDir()

src = []
if GetDepend(['BSP_USING_SD_MASTER']):
    src = Glob('*.c')

CPPPATH = [cwd]

if GetDepend(['BSP_USING_SD_MASTER']):
    group = DefineGroup('Public/Hardware/SD_Master', src, depend = [''], CPPPATH = CPPPATH)
else:
    group = []

Return('group')
